// FEATURE-FIRST content: every scene reveals a REAL, specific in-app feature the
// viewer may not know — that is what stops the scroll, not generic advice.
// Content SHAPES still vary so scenes differ structurally:
//   feature -> named app capability (shown in an app-window / phone scene)
//   stat    -> animated counter   |   bad/good -> wrong-vs-right   |   phone -> device demo
export const ACTIVE_BANKS = {
  instagram: [
    { icon: "users", feature: "Collab", head: 'پست <span class="hl">مشترک</span>', sub: 'با <b class="em">Collab</b> یک پست را با پیج دیگر منتشر کن؛ روی هر دو پیج دیده می‌شود.' },
    { icon: "layers", feature: "Reels Templates", head: 'قالب <span class="hl">آمادهٔ ریلز</span>', sub: 'در ریلز روی <b class="em">Template</b> بزن تا برش‌ها و ریتم آماده را استفاده کنی.' },
    { icon: "chat", feature: "Reply with Reel", head: 'جواب کامنت با <span class="hl">ویدیو</span>', sub: 'روی کامنت بزن و <b class="em">با ریلز جواب بده</b>؛ یک محتوای تازه رایگان می‌سازی.' },
    { icon: "star", feature: "Pin 3 posts", head: 'سنجاق <span class="hl">سه پست</span>', sub: '<b class="em">سه پست برتر</b> را بالای پیج سنجاق کن تا اولین چیزی باشد که می‌بینند.' },
    { icon: "target", feature: "Hidden Words", head: 'فیلتر <span class="hl">کامنت‌های بد</span>', sub: 'در تنظیمات، <b class="em">Hidden Words</b> را روشن کن تا کامنت‌های توهین‌آمیز خودکار پنهان شوند.' },
    { icon: "heart", feature: "Add Yours", head: 'استیکر <span class="hl">Add Yours</span>', sub: 'با استیکر <b class="em">Add Yours</b> یک زنجیرهٔ استوری بساز و مخاطب را وارد بازی کن.' },
    { icon: "bulb", feature: "Notes", head: 'یادداشت در <span class="hl">دایرکت</span>', sub: 'با <b class="em">Notes</b> یک پیام کوتاه بالای دایرکت بگذار؛ دیده‌شدن رایگان می‌گیری.' },
    { icon: "clock", feature: "Best time", head: 'ساعت <span class="hl">فعال بودن</span>', sub: 'در <b class="em">Insights</b> ببین مخاطبت چه ساعتی آنلاین است و همان موقع پست بگذار.' },
    { icon: "mic", feature: "Auto captions", head: 'زیرنویس <span class="hl">خودکار</span>', sub: 'استیکر <b class="em">Captions</b> را بگذار تا ریلز برای بی‌صداها هم قابل فهم باشد.' },
    { icon: "user", feature: "Close Friends", head: 'دوستان <span class="hl">نزدیک</span>', sub: 'با <b class="em">Close Friends</b> محتوای ویژه بگذار تا حس عضویت خاص بسازی.' },
    { icon: "layers", feature: "Collections", head: 'ذخیره در <span class="hl">مجموعه</span>', sub: 'پست‌های الهام‌بخش را در <b class="em">Collections</b> دسته‌بندی کن تا ایده تمام نشود.' },
    { icon: "globe", feature: "Links in bio", head: 'چند <span class="hl">لینک در بایو</span>', sub: 'اینستاگرام اجازه می‌دهد <b class="em">چند لینک</b> در بایو بگذاری؛ از همه‌شان استفاده کن.' },
    { icon: "star", bad: 'کاور شلوغ و ناخوانا', good: 'کاور ساده با یک تیتر درشت', head: 'کاور <span class="hl">خوانا</span>', sub: 'کاور باید <b class="em">در یک نگاه</b> خوانده شود، حتی در تصویر کوچک.' },
    { icon: "heart", stat: { value: 1, label: "استوری در روز" }, head: 'استوری <span class="hl">هر روز</span>', sub: 'حتی یک استوری در روز، <b class="em">ارتباط را زنده</b> نگه می‌دارد.' },
    { icon: "chat", bad: 'بی‌پاسخ گذاشتن کامنت‌ها', good: 'پاسخ در ساعت‌های اول', head: 'پاسخ <span class="hl">سریع</span>', sub: 'پاسخ‌دادن در ساعت‌های اول، <b class="em">تعامل پست</b> را بالا می‌برد.' },
    { icon: "play", phone: true, head: 'قدرت <span class="hl">ریلز</span>', sub: '<b class="em">ریلز</b> بیشترین شانس دیده‌شدن را دارد؛ روی آن تمرکز کن.' },
  ],
  tiktok: [
    { icon: "chat", feature: "Reply with video", head: 'جواب کامنت با <span class="hl">ویدیو</span>', sub: 'روی کامنت بزن و <b class="em">با ویدیو جواب بده</b>؛ یک ایدهٔ آمادهٔ رایگان است.' },
    { icon: "camera", feature: "Photo Mode", head: 'حالت <span class="hl">عکس</span>', sub: 'با <b class="em">Photo Mode</b> چند عکس را مثل کاروسل منتشر کن؛ زمان تماشا بالا می‌رود.' },
    { icon: "users", feature: "Stitch & Duet", head: '<span class="hl">Stitch</span> و <span class="hl">Duet</span>', sub: 'با <b class="em">Stitch یا Duet</b> روی ویدیوی پرطرفدار سوار شو و مخاطبش را بگیر.' },
    { icon: "bulb", feature: "Q&A", head: 'قابلیت <span class="hl">پرسش و پاسخ</span>', sub: 'با <b class="em">Q&amp;A</b> سؤال‌های مخاطب را جمع کن؛ هر سؤال یک ویدیوی آماده است.' },
    { icon: "mic", feature: "Text to speech", head: 'تبدیل <span class="hl">متن به صدا</span>', sub: 'با <b class="em">Text-to-speech</b> بدون ضبط صدا، روایت حرفه‌ای بساز.' },
    { icon: "wand", feature: "Green screen", head: 'افکت <span class="hl">پرده سبز</span>', sub: 'با <b class="em">Green Screen</b> عکس یا صفحه را پشت خودت بگذار و توضیح بده.' },
    { icon: "trend", feature: "Creative Center", head: 'مرکز <span class="hl">ترندها</span>', sub: 'در <b class="em">TikTok Creative Center</b> ترندها و صداهای داغ را قبل از همه ببین.' },
    { icon: "layers", feature: "Playlists", head: 'پلی‌<span class="hl">لیست</span>', sub: 'ویدیوها را در <b class="em">Playlist</b> دسته‌بندی کن تا بیننده پشت‌سرهم تماشا کند.' },
    { icon: "star", feature: "Auto captions", head: 'زیرنویس <span class="hl">خودکار</span>', sub: '<b class="em">Captions</b> را روشن کن؛ بیشتر مردم ویدیو را بی‌صدا می‌بینند.' },
    { icon: "music", feature: "Save sounds", head: 'ذخیرهٔ <span class="hl">صداهای ترند</span>', sub: 'صدای در حال ترند را <b class="em">ذخیره</b> کن تا برای ویدیوی بعدی آماده باشد.' },
    { icon: "chart", feature: "Analytics", head: 'ساعت <span class="hl">فعال بودن</span>', sub: 'در <b class="em">Analytics</b> ببین دنبال‌کننده‌هایت چه ساعتی آنلاین‌اند.' },
    { icon: "calendar", feature: "Schedule", head: 'زمان‌بندی از <span class="hl">وب</span>', sub: 'از نسخهٔ وب تیک‌تاک می‌توانی ویدیو را <b class="em">از قبل زمان‌بندی</b> کنی.' },
    { icon: "magnet", stat: { value: 3, label: "ثانیهٔ طلایی" }, head: 'قلاب <span class="hl">سه‌ثانیه‌ای</span>', sub: 'در <b class="em">سه ثانیهٔ اول</b> با یک سؤال یا جملهٔ قوی، مخاطب را نگه دار.' },
    { icon: "play", bad: 'شروع با «سلام، خوش آمدید»', good: 'شروع با نتیجه یا سؤال', head: 'شروع را <span class="hl">هدر نده</span>', sub: 'مقدمهٔ طولانی مخاطب را فراری می‌دهد؛ <b class="em">مستقیم سر اصل مطلب</b> برو.' },
    { icon: "chat", phone: true, head: 'موتور <span class="hl">کامنت</span>', sub: 'با یک <b class="em">سؤال ساده</b> در پایان ویدیو، بخش کامنت را فعال کن.' },
    { icon: "camera", bad: 'نور کم و تصویر لرزان', good: 'نور روبه‌رو و دوربین ثابت', head: 'کیفیت <span class="hl">دیده می‌شود</span>', sub: 'با <b class="em">نور کافی</b> و تصویر ثابت، حرفه‌ای‌تر به نظر می‌رسی.' },
  ],
  tools: [
    { icon: "camera", tool: "capcut.com", feature: "CapCut", head: 'ادیت با <span class="hl">CapCut</span>', sub: 'ویدیوهایت را رایگان با <b class="em">CapCut</b> برش بزن و زیرنویس بگذار.' },
    { icon: "sparkle", tool: "upscayl.org", feature: "Upscayl", head: 'کیفیت عکس را <span class="hl">بالا ببر</span>', sub: 'با <b class="em">Upscayl</b> عکس‌های کم‌کیفیت را واضح و بزرگ کن.' },
    { icon: "layers", tool: "canva.com", feature: "Canva", head: 'طراحی با <span class="hl">Canva</span>', sub: 'کاور و پست حرفه‌ای را بدون تخصص با <b class="em">Canva</b> بساز.' },
    { icon: "wand", tool: "remove.bg", feature: "remove.bg", head: 'حذف <span class="hl">پس‌زمینه</span>', sub: 'با <b class="em">remove.bg</b> در چند ثانیه پس‌زمینهٔ عکس را پاک کن.' },
    { icon: "bulb", tool: "chatgpt.com", feature: "ChatGPT", head: 'ایده با <span class="hl">هوش مصنوعی</span>', sub: 'با <b class="em">ChatGPT</b> ده‌ها ایدهٔ محتوا و کپشن بگیر.' },
    { icon: "mic", tool: "elevenlabs.io", feature: "ElevenLabs", head: 'صدای <span class="hl">مصنوعی</span>', sub: 'با <b class="em">ElevenLabs</b> برای ویدیوهایت گویندهٔ طبیعی بساز.' },
    { icon: "star", tool: "submagic.co", feature: "Submagic", head: 'زیرنویس <span class="hl">خودکار</span>', sub: 'با <b class="em">Submagic یا CapCut</b> زیرنویس هماهنگ و جذاب بساز.' },
    { icon: "wand", tool: "ideogram.ai", feature: "Ideogram", head: 'تصویر با <span class="hl">متن</span>', sub: 'با <b class="em">Ideogram</b> تصویری بساز که متن روی آن خوانا باشد.' },
    { icon: "globe", tool: "deepl.com", feature: "DeepL", head: 'ترجمهٔ <span class="hl">روان</span>', sub: 'با <b class="em">DeepL</b> محتوا را روان به زبان‌های دیگر برگردان.' },
    { icon: "calendar", tool: "business.facebook.com", feature: "Meta Suite", head: 'زمان‌بندی <span class="hl">پست‌ها</span>', sub: 'با <b class="em">Meta Business Suite</b> پست‌ها را از قبل زمان‌بندی کن.' },
    { icon: "trend", tool: "TikTok Creative Center", feature: "Creative Center", head: 'ترندها را <span class="hl">پیدا کن</span>', sub: 'در <b class="em">Creative Center</b> ترندها و صداهای داغ را ببین.' },
    { icon: "chip", bad: 'انتشار خروجی خام هوش مصنوعی', good: 'ویرایش با لحن خودت', head: 'هوش مصنوعی، <span class="hl">دستیار</span>', sub: 'خروجی را <b class="em">با لحن خودت</b> بازنویسی کن تا طبیعی بماند.' },
    { icon: "chart", phone: true, head: 'آمار را <span class="hl">بخوان</span>', sub: 'ببین کدام محتوا <b class="em">تا آخر دیده شده</b> و چرا؛ همان را تکرار کن.' },
    { icon: "bolt", bad: 'ساختن هر ویدیو از صفر', good: 'ساختن یک قالب ثابت', head: 'قالب <span class="hl">بساز</span>', sub: 'یک <b class="em">قالب آماده</b> بساز تا تولید محتوا سریع و یکدست شود.' },
    { icon: "pen", stat: { value: 1, label: "ایده، چند قالب" }, head: 'یک ایده، <span class="hl">چند پست</span>', sub: 'یک ایده را به <b class="em">ریلز، کاروسل و استوری</b> تبدیل کن.' },
    { icon: "clock", stat: { value: 30, label: "دقیقه در روز" }, head: 'زمان <span class="hl">متمرکز</span>', sub: 'روزی نیم‌ساعت تمرکز روی محتوا، از <b class="em">کار پراکنده</b> بهتر است.' },
  ],
};
