// 2026 update pack — built from what the platforms actually shipped this year,
// not from general knowledge. Sources checked in August 2026: EmbedSocial and
// Metricool feature trackers, SocialBee's monthly update logs, The Verge on
// Replace Audio, LikesPrime on the April Instagram release.
//
// Menu wording moves between app versions and regions, so each step says what
// to look for rather than reciting a fixed path.
export const Y2026 = {
  instagram: [
    {
      id: "edits-text-styles",
      benefit: { key: "seen", fa: "یک هویت ثابت بساز تا پیجت حرفه‌ای دیده شود" },
      name: "Edits Styles",
      title: "ذخیرهٔ استایل متن در Edits — افغان فالورز",
      hook: { ask: "با این آپدیت اینستاگرام، ادیت ریلزت را حرفه‌ای کن و ویو بگیر", l1: "قلم و رنگ متن را", l2: "یک‌بار بساز، همیشه استفاده کن" },
      payoff: "همهٔ ویدیوهایت یک شکل و یک هویت پیدا می‌کنند.",
      steps: [
        { path: "Edits > Projects", icon: "pen", text: "در برنامهٔ Edits پروژه‌ات را باز کن", ui: { screen: "compose", title: "Edits", cta: "باز کردن پروژه" } },
        { path: "Text > Font & Colour", icon: "pen", text: "یک متن بگذار و قلم و رنگش را دلخواه کن", ui: { screen: "list", title: "متن", rows: ["قلم", "رنگ", "اندازه"], hit: 0 } },
        { screen: {"title":"Text style","rows":["Save this style","My styles"],"hit":0}, path: "Text frame > Bookmark", icon: "star", text: "روی قاب متن، آیکون بوکمارک را بزن", ui: { screen: "list", title: "استایل متن", rows: ["ذخیرهٔ استایل", "استایل‌های من"], hit: 0 } },
        { path: "Edits > Saved styles", icon: "sparkle", text: "در پروژهٔ بعدی همان استایل را انتخاب کن", ui: { screen: "result", title: "ذخیره شد" } },
      ],
      tgTitle: "🎨 آپدیت تازهٔ Edits: استایل متن را ذخیره کن تا همهٔ ویدیوهایت یک هویت داشته باشند\n\n#instagram #Edits #editing #افغان_فالورز #viral",
    },
    {
      id: "replace-audio",
      benefit: { key: "viral", fa: "آهنگ پست قدیمی را عوض کن، لایک‌هایت هم می‌ماند" },
      name: "Replace Audio",
      title: "تعویض موسیقی پست منتشرشده — افغان فالورز",
      hook: { ask: "می‌خواهید به یک ریلز قدیمی دوباره شانس دیده‌شدن بدهید؟", l1: "بدون حذف پست", l2: "Audio آن را عوض کن" },
      payoff: "لایک و کامنت و ویو سر جایش می‌ماند؛ فقط آهنگ عوض می‌شود.",
      steps: [
        { path: "Profile > Your post", icon: "music", text: "پست یا ریلز منتشرشده‌ات را باز کن", ui: { screen: "list", title: "پست من", rows: ["تعویض صدا", "ویرایش", "آمار"], hit: 0 } },
        { screen: {"title":"Post options","rows":["Replace audio","Edit caption","Archive"],"hit":0}, path: "··· > Replace audio", icon: "refresh", text: "از منوی سه‌نقطه گزینهٔ تعویض صدا را بزن", ui: { screen: "list", title: "گزینه‌ها", rows: ["تعویض صدا (Replace Audio)", "ویرایش کپشن"], hit: 0 } },
        { path: "Music > Choose track", icon: "play", text: "آهنگ ترند امروز را انتخاب کن", ui: { screen: "compose", title: "انتخاب آهنگ", cta: "تأیید" } },
        { path: "Replace audio > Done", icon: "heart", text: "هر چند بار که بخواهی می‌توانی تکرار کنی", ui: { screen: "result", title: "صدا عوض شد" } },
      ],
      tgTitle: "🎵 آپدیت جدید: موسیقی پست‌های قدیمی را عوض کن، بدون از دست دادن لایک‌ها\n\n#instagram #newupdate #افغان_فالورز #viral",
    },
    {
      id: "reels-teleprompter",
      benefit: { key: "seen", fa: "بدون گیر کردن حرف بزن تا بیننده بماند" },
      name: "Teleprompter",
      title: "تله‌پرامپتر داخل ریلز — افغان فالورز",
      hook: { ask: "با این آپدیت اینستاگرام، بدون گیر کردن حرف بزن تا بیننده نرود", l1: "متن را از روی صفحه بخوان", l2: "بدون حفظ کردن" },
      payoff: "دیگر لازم نیست ده بار ضبط کنی تا جمله را درست بگویی.",
      steps: [
        { path: "Reels > Camera", icon: "camera", text: "دوربین ریلز را باز کن", ui: { screen: "compose", title: "ریلز جدید", cta: "دوربین" } },
        { screen: {"title":"Camera tools","rows":["Teleprompter","Timer","Speed"],"hit":0}, path: "Camera tools > Teleprompter", icon: "pen", text: "آیکون تله‌پرامپتر را بزن و متنت را بنویس", ui: { screen: "list", title: "ابزارهای دوربین", rows: ["تله‌پرامپتر", "تایمر", "سرعت"], hit: 0 } },
        { path: "Teleprompter > Speed & Size", icon: "clock", text: "سرعت حرکت و اندازهٔ متن را تنظیم کن", ui: { screen: "list", title: "تله‌پرامپتر", rows: ["سرعت متوسط", "اندازهٔ متن"], hit: 0 } },
        { path: "Camera > Record", icon: "mic", text: "ضبط کن؛ متن زیر دوربین حرکت می‌کند", ui: { screen: "result", title: "ضبط شد" } },
      ],
      tgTitle: "📜 تله‌پرامپتر داخل خود اینستاگرام؛ متن را بخوان و ضبط کن\n\n#instagram #newupdate #contentcreator #افغان_فالورز #viral",
    },
    {
      id: "reorder-grid",
      benefit: { key: "seen", fa: "بهترین کارت را اول بگذار تا غریبه فالو کند" },
      name: "Reorder Grid",
      title: "چیدمان دلخواه پروفایل — افغان فالورز",
      hook: { ask: "با این آپدیت اینستاگرام، غریبه‌ای که به پیجت می‌آید را فالوور کن", l1: "پست‌های پروفایل را", l2: "هر طور خواستی بچین" },
      payoff: "پروفایلت دیگر اسیر ترتیب تاریخ نیست؛ بهترین کارت را اول بگذار.",
      steps: [
        { path: "Profile", icon: "layers", text: "به پروفایل خودت برو", ui: { screen: "list", title: "پروفایل", rows: ["چیدمان پست‌ها", "ویرایش پروفایل"], hit: 0 } },
        { screen: {"title":"Profile options","rows":["Reorder posts","Edit profile","Archive"],"hit":0}, path: "··· > Reorder posts", icon: "target", text: "گزینهٔ چیدمان پست‌ها را باز کن", ui: { screen: "list", title: "چیدمان", rows: ["جابه‌جایی پست‌ها", "بازگشت به ترتیب تاریخ"], hit: 0 } },
        { path: "Press & drag a post", icon: "wand", text: "روی پست نگه دار و به جای دلخواه بکش", ui: { screen: "compose", title: "جابه‌جایی", cta: "نگه دار و بکش" } },
        { path: "Reorder posts > Done", icon: "star", text: "ذخیره کن؛ بازدیدکننده اول همان را می‌بیند", ui: { screen: "result", title: "چیدمان ذخیره شد" } },
      ],
      tgTitle: "🔀 آپدیت ۲۰۲۶: پست‌های پروفایلت را هر طور بخواهی بچین\n\n#instagram #newupdate #growth #افغان_فالورز #viral",
    },
    {
      id: "carousel-captions",
      benefit: { key: "viral", fa: "کاروسل تا ۹ برابر بیشتر ذخیره می‌شود" },
      name: "Slide Captions",
      title: "کپشن جدا برای هر اسلاید — افغان فالورز",
      hook: { ask: "با این آپدیت اینستاگرام، سیوِ پستت را چند برابر کن", l1: "برای هر عکس کاروسل", l2: "یک کپشن جدا بنویس" },
      payoff: "هر اسلاید حرف خودش را می‌زند؛ مخاطب تا آخر ورق می‌زند.",
      steps: [
        { path: "New post > Select photos", icon: "layers", text: "چند عکس را برای کاروسل انتخاب کن", ui: { screen: "compose", title: "پست جدید", cta: "بعدی" } },
        { screen: {"title":"Per-slide caption","rows":["Slide 1","Slide 2","Slide 3"],"hit":1}, path: "Next > Per-slide caption", icon: "pen", text: "روی هر اسلاید بزن و متن همان را بنویس", ui: { screen: "list", title: "کپشن اسلایدها", rows: ["اسلاید ۱ — متن", "اسلاید ۲ — متن"], hit: 0 } },
        { path: "Slide 2 > Write caption", icon: "chat", text: "در هر اسلاید یک نکته بگذار، نه همه را در یکی", ui: { screen: "compose", title: "اسلاید ۲", cta: "ذخیره" } },
        { path: "Share", icon: "trend", text: "منتشر کن؛ ورق‌زدن بیشتر یعنی دیده‌شدن بیشتر", ui: { screen: "result", title: "منتشر شد" } },
      ],
      tgTitle: "📑 آپدیت ۲۰۲۶: هر اسلاید کاروسل کپشن جدای خودش را دارد\n\n#instagram #newupdate #contentcreator #افغان_فالورز #viral",
    },
    {
      id: "ig-ai-translate",
      benefit: { key: "seen", fa: "ریلزت را به زبان مخاطب برسان" },
      name: "AI Translation",
      title: "ترجمهٔ ریلز با هماهنگی لب — افغان فالورز",
      hook: { ask: "با این قابلیت اینستاگرام، از چند کشور فالوور بگیر", l1: "ریلزت را به زبان دیگر", l2: "با صدای خودت بگو" },
      payoff: "صدا ترجمه می‌شود و حرکت لب هم با زبان تازه هماهنگ می‌ماند.",
      steps: [
        { path: "Reels > New reel", icon: "globe", text: "ریلز را بساز و به صفحهٔ آخر برو", ui: { screen: "compose", title: "ریلز جدید", cta: "بعدی" } },
        { screen: {"title":"Advanced settings","rows":["Translate audio","Captions","Schedule"],"hit":0}, path: "Advanced settings > Translate", icon: "mic", text: "گزینهٔ ترجمهٔ هوش مصنوعی را روشن کن", ui: { screen: "list", title: "تنظیمات پیشرفته", rows: ["ترجمهٔ خودکار صدا", "زیرنویس"], hit: 0 } },
        { path: "Translate > Choose languages", icon: "users", text: "تا دو زبان انتخاب کن", ui: { screen: "list", title: "انتخاب زبان", rows: ["انگلیسی", "آلمانی", "عربی"], hit: 0 } },
        { path: "Review > Share", icon: "target", text: "نتیجه را ببین؛ اگر لب هماهنگ نبود خاموشش کن", ui: { screen: "result", title: "ترجمه آماده شد" } },
      ],
      tgTitle: "🌍 ترجمهٔ خودکار ریلز با هماهنگی حرکت لب — آپدیت ۲۰۲۶\n\n#instagram #newupdate #ai #افغان_فالورز #viral",
    },
  ],

  tiktok: [
    {
      id: "tt-live-intro",
      benefit: { key: "seen", fa: "بیننده‌ای که وسط لایو می‌رسد را نگه دار" },
      name: "AI Live Intro",
      title: "معرفی خودکار لایو — افغان فالورز",
      hook: { ask: "با این آپدیت تیک‌تاک، ویوِ لایوت را دو برابر کن", l1: "بیننده‌ای که وسط لایو می‌آید", l2: "بفهمد اینجا چه خبر است" },
      payoff: "هر کس دیر برسد هم می‌فهمد لایو دربارهٔ چیست و می‌ماند.",
      steps: [
        { path: "Live > Go Live", icon: "play", text: "صفحهٔ ساخت لایو را باز کن", ui: { screen: "compose", title: "لایو جدید", cta: "شروع" } },
        { screen: {"title":"Live settings","rows":["Generate AI intro","Title","Topic"],"hit":0}, path: "Live settings > AI intro", icon: "wand", text: "دکمهٔ ساخت معرفی با هوش مصنوعی را بزن", ui: { screen: "list", title: "تنظیمات لایو", rows: ["ساخت معرفی خودکار", "عنوان", "موضوع"], hit: 0 } },
        { path: "AI intro > Edit text", icon: "pen", text: "متن پیشنهادی را بخوان و اگر لازم بود اصلاحش کن", ui: { screen: "compose", title: "معرفی لایو", cta: "ویرایش متن" } },
        { path: "AI intro > Turn on", icon: "users", text: "تأیید کن؛ برای بیننده‌های تازه‌وارد نشان داده می‌شود", ui: { screen: "result", title: "فعال شد" } },
      ],
      tgTitle: "🎙️ آپدیت تازهٔ تیک‌تاک: معرفی خودکار لایو با هوش مصنوعی\n\n#tiktok #live #newupdate #افغان_فالورز #viral",
    },
    {
      id: "tt-keywords",
      benefit: { key: "seen", fa: "با کلمهٔ درست در جستجوی تیک‌تاک بالا بیا" },
      name: "Keywords",
      title: "کلمات کلیدی ویدیو — افغان فالورز",
      hook: { ask: "می‌خواهید ویدیویت از TikTok Search هم View بگیرد؟", l1: "به‌جای هشتگ تصادفی", l2: "Keyword درست را پیدا کن" },
      payoff: "ویدیویت در جستجو با کلمهٔ درست بالا می‌آید، نه با حدس اپ.",
      steps: [
        { screen: {"title":"Your video","rows":["Keywords","Analytics","Share"],"hit":0}, path: "Profile > Your video", icon: "target", text: "روی ویدیوی خودت برو و تنظیماتش را باز کن", ui: { screen: "list", title: "ویدیو", rows: ["کلمات کلیدی", "تحلیل‌ها", "اشتراک‌گذاری"], hit: 0 } },
        { screen: {"title":"Keywords","rows":["Tutorial","Tips","Phone"],"hit":0}, path: "··· > Keywords", icon: "chip", text: "کلمه‌هایی که اپ خودکار داده را ببین", ui: { screen: "list", title: "کلمات کلیدی", rows: ["آموزش", "ترفند", "موبایل"], hit: 0 } },
        { path: "Keywords > Add / Block", icon: "pen", text: "کلمهٔ نامربوط را حذف و کلمهٔ درست را اضافه کن", ui: { screen: "compose", title: "افزودن کلمه", cta: "ذخیره" } },
        { path: "Keywords > Save", icon: "magnet", text: "ذخیره کن؛ حالا با همان کلمه پیدا می‌شوی", ui: { screen: "result", title: "ذخیره شد" } },
      ],
      tgTitle: "🔑 آپدیت ۲۰۲۶: خودت تعیین کن ویدیویت با چه کلمه‌ای پیدا شود\n\n#tiktok #newupdate #seo #افغان_فالورز #viral",
    },
    {
      id: "tt-media-kit",
      benefit: { key: "money", fa: "آمار پیجت را حرفه‌ای نشان بده تا برند بهت تبلیغ بدهد" },
      name: "Media Kit",
      title: "مدیا کیت داخل اپ — افغان فالورز",
      // This video is about money and credibility, so it is not dressed in the
      // TikTok palette like every other TikTok video. Ink and brass, slower
      // cards: the look of a document you hand someone, which is the subject.
      design: {
        ink: { pair: ["#12203A", "#C9A227"], paper: "#F4EFE4", tint: "rgba(201,162,39,.10)" },
        rhythm: "slow",
        mood: "craft",
      },
      // The hook names neither the platform nor the feature. Two creators with
      // the same following, one paid and one not, is the contrast the whole
      // video rests on — and the answer waits until the third card.
      hook: { ask: "دو نفر با فالوور برابر؛ یکی پول می‌گیرد، دیگری هیچ", l1: "رزومهٔ پیجت را", l2: "خود اپ برایت بسازد" },
      payoff: "برای گرفتن تبلیغ، آمار پیجت را حرفه‌ای و آماده تحویل می‌دهی.",
      steps: [
        { screen: {"title":"Profile","rows":["Creator tools","Settings and privacy","Balance"],"hit":0}, path: "Profile > Creator tools", icon: "user", text: "به بخش ابزارهای سازنده برو", ui: { screen: "list", title: "ابزارهای سازنده", rows: ["ساخت مدیا کیت", "تحلیل‌ها", "کلمات کلیدی"], hit: 0 } },
        { screen: {"title":"Creator tools","rows":["Media kit","Analytics","Promote"],"hit":0}, path: "Creator tools > Media kit", icon: "chart", text: "گزینهٔ ساخت مدیا کیت را بزن", ui: { screen: "list", title: "مدیا کیت", rows: ["ساخت خودکار", "ویرایش دستی"], hit: 0 } },
        { path: "Media kit > Edit info", icon: "pen", text: "موضوع کاری و اطلاعات تماس را اضافه کن", ui: { screen: "compose", title: "مدیا کیت", cta: "ذخیره" } },
        { path: "Media kit > Share link", icon: "rocket", text: "لینکش را برای برندها بفرست", ui: { screen: "result", title: "آماده شد" } },
      ],
      tgTitle: "💼 آپدیت ۲۰۲۶: تیک‌تاک خودش رزومهٔ پیجت را می‌سازد\n\n#tiktok #newupdate #makemoney #افغان_فالورز #viral",
    },
    {
      id: "tt-story-highlights",
      benefit: { key: "seen", fa: "استوری‌ات بعد از یک روز نرود" },
      name: "Story Highlights",
      title: "هایلایت استوری تیک‌تاک — افغان فالورز",
      hook: { ask: "با این آپدیت تیک‌تاک، از استوری‌هایت هم فالوور بگیر", l1: "استوری‌ها را", l2: "ماندگار کن" },
      payoff: "استوری بعد از یک روز نمی‌رود؛ در پروفایل می‌ماند.",
      steps: [
        { path: "Story > Post", icon: "star", text: "یک استوری بگذار", ui: { screen: "compose", title: "استوری", cta: "انتشار" } },
        { screen: {"title":"Profile","rows":["Highlights","Videos","Liked"],"hit":0}, path: "Profile > Highlights", icon: "layers", text: "از پروفایل بخش هایلایت را باز کن", ui: { screen: "list", title: "پروفایل", rows: ["هایلایت‌ها", "ویدیوها", "پسندیده‌ها"], hit: 0 } },
        { path: "Highlights > New + Name", icon: "pen", text: "استوری‌ها را در یک دسته جمع کن و نامش را بگذار", ui: { screen: "list", title: "هایلایت جدید", rows: ["افزودن استوری", "نام دسته"], hit: 0 } },
        { path: "Profile > Highlights", icon: "heart", text: "روی پروفایلت ثابت می‌ماند", ui: { screen: "result", title: "هایلایت ساخته شد" } },
      ],
      tgTitle: "📌 آپدیت ۲۰۲۶: هایلایت استوری به تیک‌تاک هم آمد\n\n#tiktok #newupdate #growth #افغان_فالورز #viral",
    },
    {
      id: "tt-ai-dubbing",
      benefit: { key: "seen", fa: "یک ویدیو بساز، مخاطب چند کشور را بگیر" },
      name: "AI Dubbing",
      title: "دوبلهٔ خودکار ویدیو — افغان فالورز",
      hook: { ask: "با این قابلیت تیک‌تاک، یک ویدیو بساز و از چند کشور ویو بگیر", l1: "ویدیویت را", l2: "به زبان دیگر دوبله کن" },
      payoff: "یک ویدیو می‌سازی و به مخاطب چند کشور می‌رسد.",
      steps: [
        { screen: {"title":"Post settings","rows":["AI dubbing","Captions","Cover"],"hit":0}, path: "Upload > Post settings", icon: "mic", text: "بعد از بارگذاری، بخش دوبله را باز کن", ui: { screen: "list", title: "بارگذاری", rows: ["دوبلهٔ هوش مصنوعی", "زیرنویس", "کاور"], hit: 0 } },
        { screen: {"title":"AI dubbing","rows":["English","Arabic","Turkish"],"hit":0}, path: "AI dubbing > Language", icon: "globe", text: "زبان مقصد را انتخاب کن", ui: { screen: "list", title: "دوبله", rows: ["انگلیسی", "عربی", "ترکی"], hit: 0 } },
        { path: "AI dubbing > Preview", icon: "play", text: "نتیجه را گوش کن و تأیید کن", ui: { screen: "compose", title: "پیش‌نمایش صدا", cta: "تأیید" } },
        { path: "Post", icon: "rocket", text: "منتشر کن؛ هر کس به زبان خودش می‌شنود", ui: { screen: "result", title: "منتشر شد" } },
      ],
      tgTitle: "🎙️ دوبلهٔ خودکار ویدیو به زبان‌های دیگر — آپدیت ۲۰۲۶\n\n#tiktok #newupdate #ai #افغان_فالورز #viral",
    },
    {
      id: "tt-health-rating",
      benefit: { key: "money", fa: "امتیاز اکانتت را پس بگیر تا درآمدت قطع نشود" },
      name: "Creator Health",
      title: "امتیاز سلامت اکانت — افغان فالورز",
      hook: { ask: "با این قابلیت تیک‌تاک بفهم چرا ویوِ ویدیوهایت افتاده", l1: "امتیاز از دست رفته را", l2: "پس بگیر" },
      payoff: "سیستم جریمهٔ قدیمی رفت؛ حالا امتیاز را برمی‌گردانی.",
      steps: [
        { screen: {"title":"Settings","rows":["Account status","Privacy","Security"],"hit":0}, path: "Settings > Account status", icon: "chip", text: "به تنظیمات و بخش وضعیت اکانت برو", ui: { screen: "list", title: "تنظیمات", rows: ["وضعیت اکانت", "حریم خصوصی"], hit: 0 } },
        { screen: {"title":"Account status","rows":["Health rating","Violations","Appeals"],"hit":0}, path: "Account status > Health rating", icon: "chart", text: "امتیاز سلامت اکانتت را ببین", ui: { screen: "list", title: "سلامت اکانت", rows: ["امتیاز فعلی: ۲۰۰", "تخلف‌ها"], hit: 0 } },
        { path: "Account status > Take quiz", icon: "bulb", text: "اگر امتیاز کم شده، آزمون قوانین را بده", ui: { screen: "compose", title: "آزمون قوانین", cta: "شروع آزمون" } },
        { path: "Account status", icon: "star", text: "با محتوای سالم امتیازت دوباره بالا می‌رود", ui: { screen: "result", title: "امتیاز بازگشت" } },
      ],
      tgTitle: "🛡️ آپدیت ۲۰۲۶: امتیاز از دست رفتهٔ اکانتت را پس بگیر\n\n#tiktok #newupdate #accountsafety #افغان_فالورز #viral",
    },
  ],

  tools: [
    {
      id: "kling-ai",
      benefit: { key: "viral", fa: "عکس ساکنت را متحرک کن تا اسکرول متوقف شود" },
      name: "Kling AI",
      title: "عکس را ویدیو کن — افغان فالورز",
      hook: { ask: "کاملاً رایگان: بدون دوربین و بازیگر کلیپ بساز و ویو بگیر", l1: "از یک عکس ساکن", l2: "ویدیوی متحرک بساز" },
      payoff: "بدون دوربین و بدون فیلم‌برداری، کلیپ متحرک داری.",
      steps: [
        { brand: {"name":"Kling AI","url":"klingai.com","color":"#111827","tagline":"Image to Video"}, path: "klingai.com", icon: "globe", text: "سایت کلینگ را باز کن؛ ثبت‌نام اعتبار رایگان می‌دهد", ui: { screen: "tool", url: "klingai.com", cta: "ثبت‌نام رایگان" } },
        { path: "Image to Video", icon: "camera", text: "عکست را بارگذاری کن", ui: { screen: "tool", url: "klingai.com", cta: "بارگذاری عکس" } },
        { path: "Describe the motion", icon: "pen", text: "بنویس چه حرکتی می‌خواهی", ui: { screen: "tool", url: "klingai.com", cta: "توضیح حرکت" } },
        { path: "Generate > Download", icon: "play", text: "ویدیو ساخته می‌شود؛ دانلود کن", ui: { screen: "tool", url: "klingai.com", cta: "دانلود" } },
      ],
      tgTitle: "🎬 عکس ساکن را با هوش مصنوعی ویدیو کن — رایگان\n\n#ai #freeapp #contentcreator #افغان_فالورز #viral",
    },
    {
      id: "adobe-podcast",
      benefit: { key: "seen", fa: "صدای تمیز یعنی بیننده ویدیو را رها نمی‌کند" },
      name: "Adobe Podcast",
      title: "صدای موبایل را استودیویی کن — افغان فالورز",
      hook: { ask: "آیا صدای بد باعث می‌شود مردم ویدیویت را زود رد کنند؟", l1: "Adobe Podcast", l2: "اپ رایگان برای صدای تمیز" },
      payoff: "صدای اتاق و همهمه می‌رود و صدایت تمیز و حرفه‌ای می‌شود.",
      steps: [
        { brand: {"name":"Adobe Podcast","url":"podcast.adobe.com","color":"#FA0F00","tagline":"Enhance Speech"}, path: "podcast.adobe.com", icon: "globe", text: "سایت ادوبی پادکست را باز کن", ui: { screen: "tool", url: "podcast.adobe.com", cta: "شروع رایگان" } },
        { path: "Enhance Speech > Upload", icon: "mic", text: "فایل صدایت را بارگذاری کن", ui: { screen: "tool", url: "podcast.adobe.com", cta: "بارگذاری صدا" } },
        { path: "Enhance", icon: "wand", text: "گزینهٔ بهبود صدا را بزن", ui: { screen: "tool", url: "podcast.adobe.com", cta: "بهبود صدا" } },
        { path: "Download", icon: "sparkle", text: "صدای تمیز را دانلود کن و در ویدیو بگذار", ui: { screen: "tool", url: "podcast.adobe.com", cta: "دانلود" } },
      ],
      tgTitle: "🎧 صدای ضبط‌شده با موبایل را استودیویی کن — رایگان\n\n#freeapp #editing #افغان_فالورز #viral",
    },
    {
      id: "suno",
      benefit: { key: "money", fa: "موسیقی اختصاصی بگذار تا ویدیوت بی‌صدا یا حذف نشود" },
      name: "Suno",
      title: "موسیقی اختصاصی بساز — افغان فالورز",
      hook: { ask: "رایگان است — موزیک اختصاصی بساز تا ویدیوت حذف نشود", l1: "برای ویدیوهایت", l2: "موسیقی اختصاصی بساز" },
      payoff: "موسیقی مال خودت است؛ نه کپی‌رایت می‌خوری نه شبیه بقیه می‌شوی.",
      steps: [
        { brand: {"name":"Suno","url":"suno.com","color":"#000000","tagline":"AI music"}, path: "suno.com", icon: "globe", text: "سایت سونو را باز کن", ui: { screen: "tool", url: "suno.com", cta: "ثبت‌نام رایگان" } },
        { path: "Create", icon: "pen", text: "حال‌وهوای موسیقی را توصیف کن", ui: { screen: "tool", url: "suno.com", cta: "نوشتن توضیح" } },
        { path: "Describe the style", icon: "music", text: "چند نسخه ساخته می‌شود؛ بهترین را انتخاب کن", ui: { screen: "tool", url: "suno.com", cta: "ساختن" } },
        { path: "Download", icon: "play", text: "دانلود کن و زیر ویدیویت بگذار", ui: { screen: "tool", url: "suno.com", cta: "دانلود" } },
      ],
      tgTitle: "🎵 موسیقی اختصاصی برای ویدیوهایت بساز — بدون کپی‌رایت\n\n#ai #freeapp #music #افغان_فالورز #viral",
    },
    {
      id: "elevenlabs",
      benefit: { key: "seen", fa: "بدون میکروفون روایت بگذار؛ ویدیوی گویا بیشتر دیده می‌شود" },
      name: "ElevenLabs",
      title: "صداگذاری با هوش مصنوعی — افغان فالورز",
      hook: { ask: "بدون هیچ هزینه‌ای، بدون میکروفون روایت حرفه‌ای بساز", l1: "متن را بنویس", l2: "صدا برایت بخواند" },
      payoff: "بدون میکروفون و بدون ضبط، ویدیویت راوی حرفه‌ای دارد.",
      steps: [
        { brand: {"name":"ElevenLabs","url":"elevenlabs.io","color":"#111111","tagline":"Text to Speech"}, path: "elevenlabs.io", icon: "globe", text: "سایت الون‌لبز را باز کن", ui: { screen: "tool", url: "elevenlabs.io", cta: "ثبت‌نام رایگان" } },
        { path: "Text to Speech", icon: "pen", text: "متن روایت را بنویس", ui: { screen: "tool", url: "elevenlabs.io", cta: "نوشتن متن" } },
        { path: "Voice library", icon: "mic", text: "صدای دلخواه را انتخاب کن", ui: { screen: "tool", url: "elevenlabs.io", cta: "انتخاب صدا" } },
        { path: "Download", icon: "play", text: "فایل صدا را دانلود کن", ui: { screen: "tool", url: "elevenlabs.io", cta: "دانلود" } },
      ],
      tgTitle: "🗣️ صداگذاری حرفه‌ای بدون میکروفون — ماهانه رایگان\n\n#ai #freeapp #editing #افغان_فالورز #viral",
    },
    {
      id: "descript",
      benefit: { key: "seen", fa: "تدوین را نصف کن تا بیشتر پست بگذاری" },
      name: "Descript",
      title: "تدوین از روی متن — افغان فالورز",
      hook: { ask: "با این اپ، ادیت یک‌ساعته را در ده دقیقه تمام کن", l1: "ویدیو را", l2: "مثل متن ویرایش کن" },
      payoff: "کلمه را از متن پاک می‌کنی، همان تکه از ویدیو هم پاک می‌شود.",
      steps: [
        { brand: {"name":"Descript","url":"descript.com","color":"#2F4BFF","tagline":"Edit by transcript"}, path: "descript.com", icon: "globe", text: "سایت دیسکریپت را باز کن", ui: { screen: "tool", url: "descript.com", cta: "شروع رایگان" } },
        { path: "New project > Upload", icon: "camera", text: "ویدیو را بارگذاری کن تا متنش نوشته شود", ui: { screen: "tool", url: "descript.com", cta: "بارگذاری ویدیو" } },
        { path: "Edit the transcript", icon: "pen", text: "جملهٔ اضافی را از متن پاک کن", ui: { screen: "tool", url: "descript.com", cta: "ویرایش متن" } },
        { path: "Export", icon: "bolt", text: "مکث‌ها و کلمات اضافی خودکار حذف می‌شوند", ui: { screen: "tool", url: "descript.com", cta: "خروجی" } },
      ],
      tgTitle: "✂️ ویدیو را مثل یک متن ویرایش کن؛ کلمه را پاک کن، تصویر هم می‌رود\n\n#freeapp #editing #ai #افغان_فالورز #viral",
    },
  ],
};
