// Third feature pack — deliberately picked to be the things creators DON'T
// already know. The first two packs cover the obvious surface (collab, hidden
// words, templates); these go after the levers that actually move a page:
// what the audience is searching for, why a video died at second three, testing
// a reel on strangers before your followers see it, and the free tools that do
// a studio's job. With this pack the daily rotation runs 11 days per category
// before a topic can come back.
export const FRESH = {
  instagram: [
    {
      id: "trial-reels",
      benefit: { key: "viral", fa: "ریلز را روی غریبه‌ها تست کن، بعد وایرالش کن" },
      name: "Trial Reels",
      title: "ریلز آزمایشی — افغان فالورز",
      hook: { l1: "ریلز را اول روی غریبه‌ها", l2: "تست کن" },
      payoff: "اگر نگرفت، فالوورهایت اصلاً آن را نمی‌بینند و پیجت ضربه نمی‌خورد.",
      steps: [
        { icon: "play", text: "ریلز را بساز و به صفحهٔ آخر برو", ui: { screen: "compose", title: "ریلز جدید", cta: "بعدی" } },
        { screen: {"title":"Advanced settings","rows":["Trial reel","Turn off comments","Schedule"],"hit":0}, icon: "chip", text: "تنظیمات پیشرفته را باز کن", ui: { screen: "list", title: "تنظیمات پیشرفته", rows: ["ریلز آزمایشی (Trial)", "خاموش‌کردن کامنت", "زمان‌بندی"], hit: 0 } },
        { icon: "target", text: "گزینهٔ ریلز آزمایشی را روشن کن", ui: { screen: "list", title: "ریلز آزمایشی", rows: ["فقط برای غیرفالوورها", "نمایش به همه"], hit: 0 } },
        { icon: "chart", text: "بعد از ۷۲ ساعت نتیجه را ببین و تصمیم بگیر", ui: { screen: "result", title: "نتیجهٔ آزمایش" } },
      ],
      tgTitle: "🧪 ریلز را اول روی غریبه‌ها تست کن، بعد به فالوورها نشان بده\n\n#اینستاگرام #ریلز #رشد_پیج #افغان_فالورز",
    },
    {
      id: "broadcast-channel",
      benefit: { key: "money", fa: "مخاطب وفادارت را جدا کن تا راحت‌تر بفروشی" },
      name: "Broadcast Channel",
      title: "کانال پخش اینستاگرام — افغان فالورز",
      hook: { l1: "یک کانال بساز", l2: "که مستقیم به مخاطب برسد" },
      payoff: "پیامت در دایرکت می‌نشیند، نه لای الگوریتم فید.",
      steps: [
        { icon: "megaphone", text: "دایرکت را باز کن و روی مداد بزن", ui: { screen: "list", title: "دایرکت", rows: ["ساخت کانال پخش", "پیام جدید", "گروه جدید"], hit: 0 } },
        { icon: "pen", text: "نام کانال را بنویس", ui: { screen: "compose", title: "کانال پخش", cta: "ساختن کانال" } },
        { icon: "users", text: "فقط تو می‌نویسی، بقیه ری‌اکشن می‌دهند", ui: { screen: "comment", title: "کانال من", rows: ["پست تازه گذاشتم 🎬", "❤️ ۲۴۰ ری‌اکشن"], hit: 0 } },
        { icon: "heart", text: "لینک کانال را در استوری بگذار", ui: { screen: "result", title: "کانال فعال شد" } },
      ],
      tgTitle: "📣 کانال پخش اینستاگرام؛ مستقیم در دایرکت مخاطب\n\n#اینستاگرام #تعامل #افغان_فالورز",
    },
    {
      id: "saved-replies",
      benefit: { key: "money", fa: "به سوال مشتری در یک ثانیه جواب بده" },
      name: "Saved Replies",
      title: "جواب‌های آماده در دایرکت — افغان فالورز",
      hook: { l1: "یک‌بار بنویس", l2: "هزار بار بفرست" },
      payoff: "جواب سوال‌های تکراری از چند دقیقه به یک ضربه می‌رسد.",
      steps: [
        { icon: "chip", text: "به تنظیمات حساب حرفه‌ای برو", ui: { screen: "list", title: "تنظیمات", rows: ["پیام‌ها و پاسخ‌ها", "حریم خصوصی", "اعلان‌ها"], hit: 0 } },
        { screen: {"title":"Messages","rows":["Saved replies","Auto reply","Filters"],"hit":0}, icon: "chat", text: "بخش جواب‌های ذخیره‌شده را باز کن", ui: { screen: "list", title: "پیام‌ها", rows: ["جواب‌های ذخیره‌شده", "پاسخ خودکار"], hit: 0 } },
        { icon: "pen", text: "متن و یک کلمهٔ میان‌بر بنویس", ui: { screen: "compose", title: "جواب جدید", cta: "ذخیره" } },
        { icon: "bolt", text: "در دایرکت میان‌بر را بزن تا متن بیاید", ui: { screen: "result", title: "ذخیره شد" } },
      ],
      tgTitle: "⚡ جواب‌های آمادهٔ دایرکت؛ یک‌بار بنویس، هزار بار بفرست\n\n#اینستاگرام #مدیریت_پیج #افغان_فالورز",
    },
    {
      id: "ig-schedule",
      benefit: { key: "seen", fa: "سر ساعت اوج منتشر کن، حتی وقتی خوابی" },
      name: "Schedule",
      title: "زمان‌بندی پست از خود اینستاگرام — افغان فالورز",
      hook: { l1: "پست را امشب بساز", l2: "فردا خودش منتشر شود" },
      payoff: "لازم نیست سر ساعت اوج، خودت آنلاین باشی.",
      steps: [
        { icon: "camera", text: "پست را بساز و به صفحهٔ آخر برو", ui: { screen: "compose", title: "پست جدید", cta: "بعدی" } },
        { screen: {"title":"Advanced settings","rows":["Schedule this post","Turn off comments"],"hit":0}, icon: "chip", text: "تنظیمات پیشرفته را باز کن", ui: { screen: "list", title: "تنظیمات پیشرفته", rows: ["زمان‌بندی این پست", "خاموش‌کردن کامنت"], hit: 0 } },
        { icon: "clock", text: "روز و ساعت انتشار را انتخاب کن", ui: { screen: "list", title: "زمان‌بندی", rows: ["فردا ۲۰:۳۰", "انتخاب تاریخ دیگر"], hit: 0 } },
        { icon: "calendar", text: "تأیید کن؛ سر ساعت خودش می‌رود", ui: { screen: "result", title: "زمان‌بندی شد" } },
      ],
      tgTitle: "🗓️ پست را امشب بساز، فردا خودش منتشر شود\n\n#اینستاگرام #مدیریت_پیج #افغان_فالورز",
    },
    {
      id: "ig-insights-retention",
      benefit: { key: "viral", fa: "بفهم کدام ثانیه بیننده را می‌پراند" },
      name: "Insights",
      title: "بفهم ویدیو کجا مُرد — افغان فالورز",
      hook: { l1: "بفهم مخاطب", l2: "کدام ثانیه می‌رود" },
      payoff: "وقتی بدانی کجا می‌روند، می‌دانی کدام ثانیه را باید عوض کنی.",
      steps: [
        { icon: "chart", text: "روی ریلز خودت بزن و آمار را باز کن", ui: { screen: "list", title: "ریلز", rows: ["مشاهدهٔ آمار", "اشتراک‌گذاری", "ویرایش"], hit: 0 } },
        { icon: "trend", text: "بخش نگه‌داشت مخاطب را ببین", ui: { screen: "list", title: "آمار", rows: ["نگه‌داشت مخاطب", "بازدیدها", "دنبال‌کننده‌های جدید"], hit: 0 } },
        { icon: "target", text: "نقطه‌ای که خط سقوط می‌کند را پیدا کن", ui: { screen: "compose", title: "نگه‌داشت", cta: "ثانیهٔ ۳ افت دارد" } },
        { icon: "bulb", text: "همان ثانیه را در ویدیوی بعدی عوض کن", ui: { screen: "result", title: "نکتهٔ کلیدی" } },
      ],
      tgTitle: "📉 بفهم مخاطب دقیقاً کدام ثانیه ویدیویت را رها می‌کند\n\n#اینستاگرام #آنالیز #رشد_پیج #افغان_فالورز",
    },
  ],

  tiktok: [
    {
      id: "search-insights",
      benefit: { key: "viral", fa: "چیزی بساز که مردم همین حالا دنبالش می‌گردند" },
      name: "Search Insights",
      title: "ببین مردم چه جستجو می‌کنند — افغان فالورز",
      hook: { l1: "محتوایی بساز", l2: "که مردم دنبالش می‌گردند" },
      payoff: "به‌جای حدس‌زدن، دقیقاً می‌سازی چیزی را که جستجو می‌شود.",
      steps: [
        { screen: {"title":"Creator tools","rows":["Search Insights","Analytics","Q&A"],"hit":0}, icon: "user", text: "به پروفایل و ابزارهای سازنده برو", ui: { screen: "list", title: "ابزارهای سازنده", rows: ["بینش جستجو (Search Insights)", "تحلیل‌ها", "پرسش و پاسخ"], hit: 0 } },
        { icon: "target", text: "موضوع‌های پرجستجو را ببین", ui: { screen: "list", title: "بینش جستجو", rows: ["پرجستجو این هفته", "مرتبط با پیج تو"], hit: 0 } },
        { icon: "magnet", text: "موضوعی را انتخاب کن که به کارت می‌خورد", ui: { screen: "compose", title: "موضوع انتخابی", cta: "ساخت ویدیو" } },
        { icon: "pen", text: "همان کلمه را در عنوان و متن روی ویدیو بنویس", ui: { screen: "result", title: "آمادهٔ انتشار" } },
      ],
      tgTitle: "🔍 ببین مردم در تیک‌تاک چه جستجو می‌کنند و همان را بساز\n\n#تیک_تاک #سئو #رشد_پیج #افغان_فالورز",
    },
    {
      id: "retention-graph",
      benefit: { key: "viral", fa: "بفهم ویدیویت کجا می‌میرد و بعدی را وایرال کن" },
      name: "Retention",
      title: "نمودار ماندگاری ویدیو — افغان فالورز",
      hook: { l1: "ویدیو کجا می‌میرد؟", l2: "نمودارش را ببین" },
      payoff: "هر افت در نمودار، یک ثانیه است که باید کوتاه یا عوض شود.",
      steps: [
        { icon: "chart", text: "روی ویدیو بزن و تحلیل‌ها را باز کن", ui: { screen: "list", title: "ویدیو", rows: ["تحلیل‌ها", "اشتراک‌گذاری", "حذف"], hit: 0 } },
        { screen: {"title":"Analytics","rows":["Viewer retention","Average watch time","Traffic"],"hit":0}, icon: "trend", text: "بخش نگه‌داشت بیننده را انتخاب کن", ui: { screen: "list", title: "تحلیل‌ها", rows: ["نگه‌داشت بیننده", "میانگین زمان تماشا", "منابع ترافیک"], hit: 0 } },
        { icon: "target", text: "جایی که خط ناگهان می‌افتد را علامت بزن", ui: { screen: "compose", title: "نگه‌داشت", cta: "افت در ثانیهٔ ۲" } },
        { icon: "bolt", text: "آن قسمت را در ویدیوی بعد حذف کن", ui: { screen: "result", title: "درس امروز" } },
      ],
      tgTitle: "📊 نمودار ماندگاری؛ بفهم ویدیویت در کدام ثانیه می‌میرد\n\n#تیک_تاک #آنالیز #تولید_محتوا #افغان_فالورز",
    },
    {
      id: "pin-comment",
      benefit: { key: "viral", fa: "با یک کامنت سنجاق‌شده تعامل را چند برابر کن" },
      name: "Pin Comment",
      title: "سنجاق کامنت خودت — افغان فالورز",
      hook: { l1: "یک قلاب دوم", l2: "در کامنت‌ها بگذار" },
      payoff: "کسی که برای کامنت‌ها آمده، با یک جملهٔ تازه دوباره جذب می‌شود.",
      steps: [
        { icon: "chat", text: "زیر ویدیوی خودت یک کامنت بگذار", ui: { screen: "comment", title: "کامنت‌ها", rows: ["قسمت دوم را ببین 👇", "عالی بود!"], hit: 0 } },
        { icon: "star", text: "روی کامنت خودت نگه دار", ui: { screen: "list", title: "گزینه‌ها", rows: ["سنجاق کردن کامنت", "کپی", "حذف"], hit: 0 } },
        { icon: "target", text: "گزینهٔ سنجاق را بزن", ui: { screen: "comment", title: "سنجاق شد", rows: ["📌 قسمت دوم را ببین 👇"], hit: 0 } },
        { icon: "magnet", text: "آنجا سوال بپرس تا کامنت بگیری", ui: { screen: "result", title: "قلاب دوم فعال شد" } },
      ],
      tgTitle: "📌 کامنت خودت را سنجاق کن؛ یک قلاب دوم رایگان\n\n#تیک_تاک #تعامل #افغان_فالورز",
    },
    {
      id: "tt-schedule",
      benefit: { key: "seen", fa: "ویدیوها را سر ساعت اوج منتشر کن، بی‌آنکه آنلاین باشی" },
      name: "Schedule",
      title: "زمان‌بندی از نسخهٔ وب — افغان فالورز",
      hook: { l1: "ویدیوهای هفته را", l2: "یک شب آماده کن" },
      payoff: "نظم انتشار بدون اینکه هر روز سر ساعت آنلاین باشی.",
      steps: [
        { icon: "globe", text: "سایت تیک‌تاک را در کامپیوتر باز کن", ui: { screen: "tool", url: "tiktok.com/upload", cta: "بارگذاری" } },
        { icon: "camera", text: "ویدیو را بارگذاری کن", ui: { screen: "tool", url: "tiktok.com/upload", cta: "انتخاب فایل" } },
        { icon: "clock", text: "گزینهٔ زمان‌بندی را روشن کن", ui: { screen: "tool", url: "tiktok.com/upload", cta: "زمان‌بندی" } },
        { icon: "calendar", text: "روز و ساعت را بگذار و تأیید کن", ui: { screen: "tool", url: "tiktok.com/upload", cta: "تأیید" } },
      ],
      tgTitle: "🕗 ویدیوهای یک هفته را یک شب زمان‌بندی کن\n\n#تیک_تاک #مدیریت_پیج #افغان_فالورز",
    },
    {
      id: "auto-translate",
      benefit: { key: "seen", fa: "با زیرنویس ترجمه‌شده از مرز زبان رد شو" },
      name: "Translate",
      title: "زیرنویس ترجمه‌شده — افغان فالورز",
      hook: { l1: "ویدیویت را", l2: "به زبان‌های دیگر برسان" },
      payoff: "مخاطبی که زبانت را نمی‌داند هم می‌تواند ویدیو را دنبال کند.",
      steps: [
        { icon: "mic", text: "بعد از بارگذاری، بخش زیرنویس را باز کن", ui: { screen: "list", title: "بارگذاری", rows: ["زیرنویس خودکار", "کاور", "تگ افراد"], hit: 0 } },
        { icon: "pen", text: "زیرنویس خودکار را بساز و غلط‌ها را درست کن", ui: { screen: "list", title: "زیرنویس", rows: ["ویرایش متن", "افزودن ترجمه"], hit: 0 } },
        { icon: "globe", text: "زبان‌های ترجمه را انتخاب کن", ui: { screen: "list", title: "ترجمه", rows: ["انگلیسی", "عربی", "ترکی"], hit: 0 } },
        { icon: "rocket", text: "منتشر کن؛ هر کس به زبان خودش می‌بیند", ui: { screen: "result", title: "منتشر شد" } },
      ],
      tgTitle: "🌍 زیرنویس ترجمه‌شده؛ ویدیویت را از مرز زبان رد کن\n\n#تیک_تاک #رشد_پیج #افغان_فالورز",
    },
  ],

  tools: [
    {
      id: "cleanup-pictures",
      benefit: { key: "seen", fa: "هر چیز اضافی را از عکس پاک کن" },
      name: "Cleanup",
      title: "حذف شیء اضافی از عکس — افغان فالورز",
      hook: { l1: "هرچه اضافه است", l2: "از عکس پاک کن" },
      payoff: "آدم یا شیء اضافی می‌رود و جایش خودکار پر می‌شود.",
      steps: [
        { brand: {"name":"Cleanup","url":"cleanup.pictures","color":"#7C3AED","tagline":"Remove objects"}, path: "cleanup.pictures", icon: "globe", text: "سایت کلین‌آپ پیکچرز را باز کن", ui: { screen: "tool", url: "cleanup.pictures", cta: "بارگذاری عکس" } },
        { path: "Upload image", icon: "camera", text: "عکس را بارگذاری کن", ui: { screen: "tool", url: "cleanup.pictures", cta: "انتخاب فایل" } },
        { path: "Brush over the object", icon: "pen", text: "روی چیز اضافی قلم بکش", ui: { screen: "tool", url: "cleanup.pictures", cta: "پاک کردن" } },
        { path: "Download", icon: "sparkle", text: "پس‌زمینه خودکار پر می‌شود؛ دانلود کن", ui: { screen: "tool", url: "cleanup.pictures", cta: "دانلود" } },
      ],
      tgTitle: "🧹 هر چیز اضافی را از عکس پاک کن؛ رایگان و آنلاین\n\n#ابزار_رایگان #ویرایش_عکس #افغان_فالورز",
    },
    {
      id: "photopea",
      benefit: { key: "seen", fa: "بدون نصب و بدون پول، کاور حرفه‌ای بساز" },
      name: "Photopea",
      title: "فتوشاپ رایگان در مرورگر — افغان فالورز",
      hook: { l1: "فتوشاپ کامل", l2: "بدون نصب و بدون پول" },
      payoff: "فایل‌های PSD را هم باز می‌کند؛ نصب و اشتراک لازم نیست.",
      steps: [
        { brand: {"name":"Photopea","url":"photopea.com","color":"#18A497","tagline":"Free photo editor"}, path: "photopea.com", icon: "globe", text: "سایت فتوپیا را باز کن", ui: { screen: "tool", url: "photopea.com", cta: "شروع" } },
        { path: "File > Open", icon: "layers", text: "عکس یا فایل PSD را بکش داخلش", ui: { screen: "tool", url: "photopea.com", cta: "باز کردن فایل" } },
        { path: "Layers panel", icon: "wand", text: "لایه‌ها و ابزارها مثل فتوشاپ کار می‌کنند", ui: { screen: "tool", url: "photopea.com", cta: "ویرایش" } },
        { path: "File > Export as > PNG", icon: "star", text: "خروجی را در اندازهٔ دلخواه ذخیره کن", ui: { screen: "tool", url: "photopea.com", cta: "ذخیره PNG" } },
      ],
      tgTitle: "🎨 فتوشاپ کامل و رایگان، بدون نصب — Photopea\n\n#ابزار_رایگان #دیزاین #افغان_فالورز",
    },
    {
      id: "google-trends",
      benefit: { key: "viral", fa: "قبل از همه بفهم چه موضوعی داغ است" },
      name: "Google Trends",
      title: "موضوعی بساز که داغ است — افغان فالورز",
      hook: { l1: "قبل از ساخت", l2: "ببین چه داغ است" },
      payoff: "روی موجی سوار می‌شوی که همین حالا بالا می‌آید.",
      steps: [
        { brand: {"name":"Google Trends","url":"trends.google.com","color":"#4285F4","tagline":"What is trending"}, path: "trends.google.com", icon: "globe", text: "گوگل ترندز را باز کن", ui: { screen: "tool", url: "trends.google.com", cta: "شروع" } },
        { path: "Region selector", icon: "target", text: "کشور خودت را انتخاب کن", ui: { screen: "tool", url: "trends.google.com", cta: "انتخاب کشور" } },
        { path: "Trending now", icon: "trend", text: "موضوع‌های در حال رشد را ببین", ui: { screen: "tool", url: "trends.google.com", cta: "جستجوهای داغ" } },
        { path: "Explore", icon: "rocket", text: "همان روز دربارهٔ آن محتوا بساز", ui: { screen: "tool", url: "trends.google.com", cta: "ذخیرهٔ موضوع" } },
      ],
      tgTitle: "🔥 قبل از ساخت محتوا ببین چه موضوعی داغ است\n\n#ابزار_رایگان #ایده_محتوا #افغان_فالورز",
    },
    {
      id: "pexels-broll",
      benefit: { key: "viral", fa: "ویدیوی سینمایی رایگان بگیر بدون دوربین" },
      name: "Pexels",
      title: "ویدیوی رایگان برای پس‌زمینه — افغان فالورز",
      hook: { l1: "ویدیوی باکیفیت", l2: "رایگان و بدون کپی‌رایت" },
      payoff: "ویدیوی حرفه‌ای می‌گیری بدون دوربین و بدون هزینه.",
      steps: [
        { brand: {"name":"Pexels","url":"pexels.com/videos","color":"#05A081","tagline":"Free stock video"}, path: "pexels.com/videos", icon: "globe", text: "سایت پکسلز را باز کن", ui: { screen: "tool", url: "pexels.com/videos", cta: "جستجو" } },
        { path: "Search bar", icon: "target", text: "موضوع دلخواهت را جستجو کن", ui: { screen: "tool", url: "pexels.com/videos", cta: "جستجو" } },
        { path: "Filters > Vertical", icon: "phone", text: "فیلتر عمودی را بزن تا برای ریلز جور شود", ui: { screen: "tool", url: "pexels.com/videos", cta: "عمودی" } },
        { path: "Free Download", icon: "play", text: "دانلود کن و در تدوین استفاده کن", ui: { screen: "tool", url: "pexels.com/videos", cta: "دانلود" } },
      ],
      tgTitle: "🎥 ویدیوی حرفه‌ای و رایگان برای پس‌زمینهٔ ریلز\n\n#ابزار_رایگان #تدوین #افغان_فالورز",
    },
    {
      id: "ai-hook-writer",
      benefit: { key: "viral", fa: "ده شروع قوی بساز تا اسکرول متوقف شود" },
      name: "AI Hooks",
      title: "ده قلاب در یک دقیقه — افغان فالورز",
      hook: { l1: "برای هر ویدیو", l2: "ده شروع متفاوت بساز" },
      payoff: "شروع ویدیو مهم‌ترین سه ثانیه است؛ حالا ده گزینه داری.",
      steps: [
        { path: "claude.ai", icon: "globe", text: "یک دستیار هوش مصنوعی را باز کن", ui: { screen: "tool", url: "claude.ai", cta: "شروع گفتگو" } },
        { path: "New chat", icon: "pen", text: "موضوع ویدیو را بنویس", ui: { screen: "tool", url: "claude.ai", cta: "نوشتن موضوع" } },
        { path: "Ask for 10 hooks", icon: "bulb", text: "بخواه ده جملهٔ شروع کوتاه بسازد", ui: { screen: "tool", url: "claude.ai", cta: "ساخت ایده" } },
        { path: "Copy the best", icon: "magnet", text: "بهترین را بردار و همان را اول ویدیو بگو", ui: { screen: "tool", url: "claude.ai", cta: "انتخاب" } },
      ],
      tgTitle: "🪝 ده شروع متفاوت برای ویدیویت، در یک دقیقه\n\n#هوش_مصنوعی #تولید_محتوا #افغان_فالورز",
    },
  ],
};
