// Third feature pack — deliberately picked to be the things creators DON'T
// already know. The first two packs cover the obvious surface (collab, hidden
// words, templates); these go after the levers that actually move a page:
// what the audience is searching for, why a video died at second three, testing
// a reel on strangers before your followers see it, and the free tools that do
// a studio's job. With this pack the daily rotation runs 11 days per category
// before a topic can come back.
export const FRESH = {
  instagram: [
    {
      id: "trial-reels",
      benefit: { key: "viral", fa: "ریلز را اول برای مخاطب تازه آزمایش کن" },
      name: "Trial Reels",
      title: "ریلز آزمایشی — افغان فالورز",
      hook: {
        ask: "ریلزت را اول به غریبه‌ها نشان بده، بعد به فالوورها",
        l1: "ریلز را اول برای", l2: "مخاطب تازه تست کن",
        badge: "Instagram • Trial Reels",
      },
      payoff: "Trial Reel ابتدا به افراد غیر‌فالوور نشان داده می‌شود؛ نتیجه را ببین، بعد خودت تصمیم بگیر.",
      steps: [
        {
          screen: { title: "New reel", rows: ["Camera", "Add media", "Next"], hit: 2 },
          path: "Reel > Next", icon: "camera",
          text: "Reel را بساز یا ویدیویت را Add media کن؛ سپس Next را بزن",
        },
        {
          screen: { title: "Share", rows: ["Caption", "Trial", "Share"], hit: 1 },
          path: "Share > Trial", icon: "toggle",
          text: "در صفحهٔ Share، گزینهٔ Trial را پیدا کن و روشنش کن",
        },
        {
          screen: { title: "Trial reel insights", rows: ["Views", "Likes", "Shares"], hit: 0 },
          path: "Profile > Trial reel > View insights", icon: "chart",
          text: "حدود ۲۴ ساعت بعد، View و Share آن را در Trial reel insights ببین",
        },
        {
          screen: { title: "Trial reel", rows: ["Share with everyone", "Auto-share after 72 hours", "Keep as trial"], hit: 0 },
          path: "Trial reel > Share with everyone", icon: "send",
          text: "اگر نتیجه خوب بود، Share with everyone را بزن تا برای فالوورها هم منتشر شود",
        },
      ],
      tgTitle: "🧪 ریلزت View نمی‌گیرد؟ پیش از نشر عمومی، با Trial Reels آن را برای مخاطب تازه امتحان کن.\n\n#Instagram #Reels #TrialReels #ContentCreator #viral",
    },
    {
      id: "broadcast-channel",
      benefit: { key: "money", fa: "مخاطب وفادارت را جدا کن تا راحت‌تر بفروشی" },
      name: "Broadcast Channel",
      title: "کانال پخش اینستاگرام — افغان فالورز",
      hook: { ask: "با این قابلیت اینستاگرام، از فالوور وفادارت درآمد بساز", l1: "یک کانال بساز", l2: "که مستقیم به مخاطب برسد" },
      payoff: "پیامت در دایرکت می‌نشیند، نه لای الگوریتم فید.",
      steps: [
        { icon: "megaphone", text: "دایرکت را باز کن و روی مداد بزن", ui: { screen: "list", title: "دایرکت", rows: ["ساخت کانال پخش", "پیام جدید", "گروه جدید"], hit: 0 } },
        { icon: "pen", text: "نام کانال را بنویس", ui: { screen: "compose", title: "کانال پخش", cta: "ساختن کانال" } },
        { icon: "users", text: "فقط تو می‌نویسی، بقیه ری‌اکشن می‌دهند", ui: { screen: "comment", title: "کانال من", rows: ["پست تازه گذاشتم 🎬", "❤️ ۲۴۰ ری‌اکشن"], hit: 0 } },
        { icon: "heart", text: "لینک کانال را در استوری بگذار", ui: { screen: "result", title: "کانال فعال شد" } },
      ],
      tgTitle: "📣 کانال پخش اینستاگرام؛ مستقیم در دایرکت مخاطب\n\n#instagram #engagement #افغان_فالورز #viral",
    },
    {
      id: "saved-replies",
      benefit: { key: "money", fa: "به سؤال مشتری در یک ثانیه جواب بده" },
      name: "Saved Replies",
      title: "جواب‌های آماده در دایرکت — افغان فالورز",
      hook: { ask: "با این قابلیت اینستاگرام، دایرکت‌ها را سریع جواب بده و مشتری از دست نده", l1: "یک‌بار بنویس", l2: "هزار بار بفرست" },
      payoff: "جواب سوال‌های تکراری از چند دقیقه به یک ضربه می‌رسد.",
      steps: [
        { icon: "chip", text: "به تنظیمات حساب حرفه‌ای برو", ui: { screen: "list", title: "تنظیمات", rows: ["پیام‌ها و پاسخ‌ها", "حریم خصوصی", "اعلان‌ها"], hit: 0 } },
        { screen: {"title":"Messages","rows":["Saved replies","Auto reply","Filters"],"hit":0}, icon: "chat", text: "بخش جواب‌های ذخیره‌شده را باز کن", ui: { screen: "list", title: "پیام‌ها", rows: ["جواب‌های ذخیره‌شده", "پاسخ خودکار"], hit: 0 } },
        { icon: "pen", text: "متن و یک کلمهٔ میان‌بر بنویس", ui: { screen: "compose", title: "جواب جدید", cta: "ذخیره" } },
        { icon: "bolt", text: "در دایرکت میان‌بر را بزن تا متن بیاید", ui: { screen: "result", title: "ذخیره شد" } },
      ],
      tgTitle: "⚡ جواب‌های آمادهٔ دایرکت؛ یک‌بار بنویس، هزار بار بفرست\n\n#instagram #socialmediatips #افغان_فالورز #viral",
    },
    {
      id: "ig-schedule",
      benefit: { key: "seen", fa: "بین ۷ تا ۹ شب منتشر کن، حتی وقتی خوابی" },
      name: "Schedule",
      title: "زمان‌بندی پست از خود اینستاگرام — افغان فالورز",
      hook: { ask: "پستت را سر ساعت اوج بگذار و ویو بیشتر بگیر، حتی وقتی خوابی", l1: "پست را امشب بساز", l2: "فردا خودش منتشر شود" },
      payoff: "لازم نیست سر ساعت اوج، خودت آنلاین باشی.",
      steps: [
        { icon: "camera", text: "پست را بساز و به صفحهٔ آخر برو", ui: { screen: "compose", title: "پست جدید", cta: "بعدی" } },
        { screen: {"title":"Advanced settings","rows":["Schedule this post","Turn off comments"],"hit":0}, icon: "chip", text: "تنظیمات پیشرفته را باز کن", ui: { screen: "list", title: "تنظیمات پیشرفته", rows: ["زمان‌بندی این پست", "خاموش‌کردن کامنت"], hit: 0 } },
        { icon: "clock", text: "روز و ساعت انتشار را انتخاب کن", ui: { screen: "list", title: "زمان‌بندی", rows: ["فردا ۲۰:۳۰", "انتخاب تاریخ دیگر"], hit: 0 } },
        { icon: "calendar", text: "تأیید کن؛ سر ساعت خودش می‌رود", ui: { screen: "result", title: "زمان‌بندی شد" } },
      ],
      tgTitle: "🗓️ پست را امشب بساز، فردا خودش منتشر شود\n\n#instagram #socialmediatips #افغان_فالورز #viral",
    },
    {
      id: "ig-insights-retention",
      benefit: { key: "viral", fa: "بفهم ویدیویت کجا می‌میرد" },
      name: "Insights",
      title: "بفهم ویدیو کجا مُرد — افغان فالورز",
      hook: { ask: "با این قابلیت اینستاگرام، جای دقیق افت ویوَت را پیدا کن", l1: "بفهم مخاطب", l2: "کدام ثانیه می‌رود" },
      payoff: "وقتی بدانی کجا می‌روند، می‌دانی کدام ثانیه را باید عوض کنی.",
      steps: [
        { icon: "chart", text: "روی ریلز خودت بزن و آمار را باز کن", ui: { screen: "list", title: "ریلز", rows: ["مشاهدهٔ آمار", "اشتراک‌گذاری", "ویرایش"], hit: 0 } },
        { icon: "trend", text: "بخش نگه‌داشت مخاطب را ببین", ui: { screen: "list", title: "آمار", rows: ["نگه‌داشت مخاطب", "بازدیدها", "دنبال‌کننده‌های جدید"], hit: 0 } },
        { icon: "target", text: "نقطه‌ای که خط سقوط می‌کند را پیدا کن", ui: { screen: "compose", title: "نگه‌داشت", cta: "ثانیهٔ ۳ افت دارد" } },
        { icon: "bulb", text: "همان ثانیه را در ویدیوی بعدی عوض کن", ui: { screen: "result", title: "نکتهٔ کلیدی" } },
      ],
      tgTitle: "📉 بفهم مخاطب دقیقاً کدام ثانیه ویدیویت را رها می‌کند\n\n#instagram #analytics #growth #افغان_فالورز #viral",
    },
  ],

  tiktok: [
    {
      id: "tiktok-shop-video-assistant",
      benefit: { key: "money", fa: "ویدیوی فروش بساز، بدون گیرماندن در ایده و متن" },
      name: "TikTok Shop Video Assistant",
      title: "Video Assistant تیک‌تاک شاپ — افغان فالورز",
      hook: {
        ask: "برای محصولت ویدیو می‌سازی، اما از TikTok Shop فروش نمی‌گیری؟",
        l1: "ویدیوی فروش بساز", l2: "بدون گیرماندن در ایده و متن",
        badge: "آپدیت تازهٔ TikTok Shop",
      },
      // This photograph is a generated presenter visual, never passed off as a
      // TikTok screenshot. The app navigation itself is recreated from the
      // current Germany help page and stays inside the phone frames below.
      hookPhoto: { src: "public/video-assistant-creator.png" },
      payoff: "Video Assistant برایت متن، Hook و نکته‌های محصول می‌سازد؛ نتیجهٔ فروش تضمین نیست.",
      steps: [
        {
          screen: { title: "TikTok Shop", rows: ["Creator Center", "Orders", "Shop Toolkit"], hit: 0 },
          path: "Profile > TikTok Shop > Creator Center",
          icon: "shop", text: "Profile را باز کن، روی آیکن کیف خرید بزن و Creator Center را انتخاب کن",
        },
        {
          screen: { title: "Creator Center", rows: ["Videos", "Create now", "Products"], hit: 0 },
          path: "Creator Center > Videos",
          icon: "play", text: "در پایین صفحه Videos را باز کن؛ اینجا ویدیوی فروش ساخته می‌شود",
        },
        {
          screen: { title: "Create", rows: ["Video Assistant", "Short video", "Teleprompter"], hit: 0 },
          path: "Videos > Video Assistant",
          icon: "chip", text: "زیر بخش Create روی Video Assistant بزن و محصولت را انتخاب کن",
        },
        {
          screen: { title: "Video Assistant", rows: ["Write a full script", "Recommend hashtags", "Record with this script"], hit: 0 },
          path: "Video Assistant > Write a full script",
          icon: "write", text: "Script و Hook را بساز، Edit کن و با Teleprompter ویدیویت را ضبط کن",
        },
      ],
      tgTitle: "🛍️ آپدیت تازهٔ TikTok Shop: Video Assistant برای Script، Hook و ویدیوی فروش\n\n#TikTokShop #VideoAssistant #tiktokshop #افغان_فالورز #viral",
    },
    {
      id: "search-insights",
      benefit: { key: "viral", fa: "چیزی بساز که مردم همین حالا جستجو می‌کنند" },
      name: "Creator Search Insights",
      title: "از Search تیک‌تاک ویو بگیر — افغان فالورز",
      hookPhoto: "public/official-ui/tiktok-search-analytics.png",
      hook: { ask: "می‌خواهید ویدیویتان از Search تیک‌تاک ویو بگیرد؟", l1: "ویو از Search", l2: "نه فقط For You" },
      payoff: "به‌جای حدس‌زدن، موضوعی را انتخاب می‌کنی که مردم واقعاً دنبالش هستند.",
      steps: [
        { path: "Search > creator search insights", icon: "target", text: "بالای TikTok روی Search بزن و Creator Search Insights را بنویس", photo: "public/official-ui/tiktok-search-analytics.png", photoFocus: "search" },
        { path: "Creator Search Insights", icon: "play", text: "صفحه را باز کن؛ اینجا موضوع‌هایی را می‌بینی که مردم واقعاً Search می‌کنند", photo: "public/official-ui/tiktok-search-analytics.png", photoFocus: "search" },
        { path: "Creator Search Insights > Content gap", icon: "chart", text: "Content gap را بزن تا موضوعِ پرجستجو اما کم‌محتوا را پیدا کنی", photo: "public/official-ui/tiktok-search-analytics.png", photoFocus: "gap" },
        { path: "Search analytics", icon: "pen", text: "بعد از انتشار، Search analytics را ببین تا بفهمی کدام موضوع برایت ویو آورده", photo: "public/official-ui/tiktok-search-analytics.png", photoFocus: "analytics" },
      ],
      tgTitle: "🔍 ببین مردم در تیک‌تاک چه جستجو می‌کنند و همان را بساز\n\n#tiktok #seo #growth #افغان_فالورز #viral",
    },
    {
      id: "retention-graph",
      benefit: { key: "viral", fa: "بفهم کدام ثانیه بیننده را می‌پراند" },
      name: "Retention",
      title: "نمودار ماندگاری ویدیو — افغان فالورز",
      hook: { ask: "بفهم بیننده کدام ثانیه ویدیویت را رها می‌کند", l1: "ویدیو کجا می‌میرد؟", l2: "نمودارش را ببین" },
      payoff: "هر افت در نمودار، یک ثانیه است که باید کوتاه یا عوض شود.",
      steps: [
        { icon: "chart", text: "روی ویدیو بزن و تحلیل‌ها را باز کن", ui: { screen: "list", title: "ویدیو", rows: ["تحلیل‌ها", "اشتراک‌گذاری", "حذف"], hit: 0 } },
        { screen: {"title":"Analytics","rows":["Viewer retention","Average watch time","Traffic"],"hit":0}, icon: "trend", text: "بخش نگه‌داشت بیننده را انتخاب کن", ui: { screen: "list", title: "تحلیل‌ها", rows: ["نگه‌داشت بیننده", "میانگین زمان تماشا", "منابع ترافیک"], hit: 0 } },
        { icon: "target", text: "جایی که خط ناگهان می‌افتد را علامت بزن", ui: { screen: "compose", title: "نگه‌داشت", cta: "افت در ثانیهٔ ۲" } },
        { icon: "bolt", text: "آن قسمت را در ویدیوی بعد حذف کن", ui: { screen: "result", title: "درس امروز" } },
      ],
      tgTitle: "📊 نمودار ماندگاری؛ بفهم ویدیویت در کدام ثانیه می‌میرد\n\n#tiktok #analytics #contentcreator #افغان_فالورز #viral",
    },
    {
      id: "pin-comment",
      benefit: { key: "viral", fa: "سؤال بپرس؛ کامنت‌ها تا ۲۶٪ بالا می‌رود" },
      name: "Pin Comment",
      title: "سنجاق کامنت خودت — افغان فالورز",
      hook: { ask: "با این ترفند ساده، کامنت و ویوِ ویدیوهایت را چند برابر کن", l1: "یک قلاب دوم", l2: "در کامنت‌ها بگذار" },
      payoff: "کسی که برای کامنت‌ها آمده، با یک جملهٔ تازه دوباره جذب می‌شود.",
      steps: [
        { icon: "chat", text: "زیر ویدیوی خودت یک کامنت بگذار", ui: { screen: "comment", title: "کامنت‌ها", rows: ["قسمت دوم را ببین 👇", "عالی بود!"], hit: 0 } },
        { icon: "star", text: "روی کامنت خودت نگه دار", ui: { screen: "list", title: "گزینه‌ها", rows: ["سنجاق کردن کامنت", "کپی", "حذف"], hit: 0 } },
        { icon: "target", text: "گزینهٔ سنجاق را بزن", ui: { screen: "comment", title: "سنجاق شد", rows: ["📌 قسمت دوم را ببین 👇"], hit: 0 } },
        { icon: "magnet", text: "آنجا سوال بپرس تا کامنت بگیری", ui: { screen: "result", title: "قلاب دوم فعال شد" } },
      ],
      tgTitle: "📌 کامنت خودت را سنجاق کن؛ یک قلاب دوم رایگان\n\n#tiktok #engagement #افغان_فالورز #viral",
    },
    {
      id: "tt-schedule",
      benefit: { key: "seen", fa: "بین ۶ تا ۹ شب پست کن؛ بهترین ساعت ۸ است" },
      name: "Schedule",
      title: "زمان‌بندی از نسخهٔ وب — افغان فالورز",
      hook: { ask: "ویدیویت را سر ساعت اوج پست کن و ویو بیشتر بگیر", l1: "ویدیوهای هفته را", l2: "یک شب آماده کن" },
      payoff: "نظم انتشار بدون اینکه هر روز سر ساعت آنلاین باشی.",
      steps: [
        { icon: "globe", text: "سایت تیک‌تاک را در کامپیوتر باز کن", ui: { screen: "tool", url: "tiktok.com/upload", cta: "بارگذاری" } },
        { icon: "camera", text: "ویدیو را بارگذاری کن", ui: { screen: "tool", url: "tiktok.com/upload", cta: "انتخاب فایل" } },
        { icon: "clock", text: "گزینهٔ زمان‌بندی را روشن کن", ui: { screen: "tool", url: "tiktok.com/upload", cta: "زمان‌بندی" } },
        { icon: "calendar", text: "روز و ساعت را بگذار و تأیید کن", ui: { screen: "tool", url: "tiktok.com/upload", cta: "تأیید" } },
      ],
      tgTitle: "🕗 ویدیوهای یک هفته را یک شب زمان‌بندی کن\n\n#tiktok #socialmediatips #افغان_فالورز #viral",
    },
    {
      id: "auto-translate",
      benefit: { key: "seen", fa: "زیرنویس ترجمه‌شده مخاطبت را چند برابر می‌کند" },
      name: "Translate",
      title: "زیرنویس ترجمه‌شده — افغان فالورز",
      hook: { ask: "با این قابلیت تیک‌تاک، از کشورهای دیگر هم ویو بگیر", l1: "ویدیویت را", l2: "به زبان‌های دیگر برسان" },
      payoff: "مخاطبی که زبانت را نمی‌داند هم می‌تواند ویدیو را دنبال کند.",
      steps: [
        { icon: "mic", text: "بعد از بارگذاری، بخش زیرنویس را باز کن", ui: { screen: "list", title: "بارگذاری", rows: ["زیرنویس خودکار", "کاور", "تگ افراد"], hit: 0 } },
        { icon: "pen", text: "زیرنویس خودکار را بساز و غلط‌ها را درست کن", ui: { screen: "list", title: "زیرنویس", rows: ["ویرایش متن", "افزودن ترجمه"], hit: 0 } },
        { icon: "globe", text: "زبان‌های ترجمه را انتخاب کن", ui: { screen: "list", title: "ترجمه", rows: ["انگلیسی", "عربی", "ترکی"], hit: 0 } },
        { icon: "rocket", text: "منتشر کن؛ هر کس به زبان خودش می‌بیند", ui: { screen: "result", title: "منتشر شد" } },
      ],
      tgTitle: "🌍 زیرنویس ترجمه‌شده؛ ویدیویت را از مرز زبان رد کن\n\n#tiktok #growth #افغان_فالورز #viral",
    },
  ],

  tools: [
    {
      id: "cleanup-pictures",
      benefit: { key: "seen", fa: "عکس تمیز، کاور بهتر و کلیک بیشتر" },
      name: "Cleanup",
      title: "حذف شیء اضافی از عکس — افغان فالورز",
      hook: { ask: "رایگان و بدون نصب: هر چیز اضافی را از عکست پاک کن", l1: "هرچه اضافه است", l2: "از عکس پاک کن" },
      payoff: "آدم یا شیء اضافی می‌رود و جایش خودکار پر می‌شود.",
      steps: [
        { brand: {"name":"Cleanup","url":"cleanup.pictures","color":"#7C3AED","tagline":"Remove objects"}, path: "cleanup.pictures", icon: "globe", text: "سایت کلین‌آپ پیکچرز را باز کن", ui: { screen: "tool", url: "cleanup.pictures", cta: "بارگذاری عکس" } },
        { path: "Upload image", icon: "camera", text: "عکس را بارگذاری کن", ui: { screen: "tool", url: "cleanup.pictures", cta: "انتخاب فایل" } },
        { path: "Brush over the object", icon: "pen", text: "روی چیز اضافی قلم بکش", ui: { screen: "tool", url: "cleanup.pictures", cta: "پاک کردن" } },
        { path: "Download", icon: "sparkle", text: "پس‌زمینه خودکار پر می‌شود؛ دانلود کن", ui: { screen: "tool", url: "cleanup.pictures", cta: "دانلود" } },
      ],
      tgTitle: "🧹 هر چیز اضافی را از عکس پاک کن؛ رایگان و آنلاین\n\n#freeapp #photoediting #افغان_فالورز #viral",
    },
    {
      id: "photopea",
      benefit: { key: "seen", fa: "کاور حرفه‌ای بساز، بدون نصب و بدون پول" },
      name: "Photopea",
      title: "فتوشاپ رایگان در مرورگر — افغان فالورز",
      hook: { ask: "این اپ رایگان است — بدون خریدن فتوشاپ عکس‌هایت را حرفه‌ای کن", l1: "فتوشاپ کامل", l2: "بدون نصب و بدون پول" },
      payoff: "فایل‌های PSD را هم باز می‌کند؛ نصب و اشتراک لازم نیست.",
      steps: [
        { brand: {"name":"Photopea","url":"photopea.com","color":"#18A497","tagline":"Free photo editor"}, path: "photopea.com", icon: "globe", text: "سایت فتوپیا را باز کن", ui: { screen: "tool", url: "photopea.com", cta: "شروع" } },
        { path: "File > Open", icon: "layers", text: "عکس یا فایل PSD را بکش داخلش", ui: { screen: "tool", url: "photopea.com", cta: "باز کردن فایل" } },
        { path: "Layers panel", icon: "wand", text: "لایه‌ها و ابزارها مثل فتوشاپ کار می‌کنند", ui: { screen: "tool", url: "photopea.com", cta: "ویرایش" } },
        { path: "File > Export as > PNG", icon: "star", text: "خروجی را در اندازهٔ دلخواه ذخیره کن", ui: { screen: "tool", url: "photopea.com", cta: "ذخیره PNG" } },
      ],
      tgTitle: "🎨 فتوشاپ کامل و رایگان، بدون نصب — Photopea\n\n#freeapp #design #افغان_فالورز #viral",
    },
    {
      id: "google-trends",
      benefit: { key: "viral", fa: "قبل از موج سوار شو، نه بعد از آن" },
      name: "Google Trends",
      title: "موضوعی بساز که داغ است — افغان فالورز",
      hook: { ask: "رایگان است — قبل از همه سوار ترند شو و وایرال شو", l1: "قبل از ساخت", l2: "ببین چه داغ است" },
      payoff: "روی موجی سوار می‌شوی که همین حالا بالا می‌آید.",
      steps: [
        { brand: {"name":"Google Trends","url":"trends.google.com","color":"#4285F4","tagline":"What is trending"}, path: "trends.google.com", icon: "globe", text: "گوگل ترندز را باز کن", ui: { screen: "tool", url: "trends.google.com", cta: "شروع" } },
        { path: "Region selector", icon: "target", text: "کشور خودت را انتخاب کن", ui: { screen: "tool", url: "trends.google.com", cta: "انتخاب کشور" } },
        { path: "Trending now", icon: "trend", text: "موضوع‌های در حال رشد را ببین", ui: { screen: "tool", url: "trends.google.com", cta: "جستجوهای داغ" } },
        { path: "Explore", icon: "rocket", text: "همان روز دربارهٔ آن محتوا بساز", ui: { screen: "tool", url: "trends.google.com", cta: "ذخیرهٔ موضوع" } },
      ],
      tgTitle: "🔥 قبل از ساخت محتوا ببین چه موضوعی داغ است\n\n#freeapp #contentideas #افغان_فالورز #viral",
    },
    {
      id: "pexels-broll",
      benefit: { key: "viral", fa: "تصویر سینمایی بگذار بدون اینکه دوربین داشته باشی" },
      name: "Pexels",
      title: "ویدیوی رایگان برای پس‌زمینه — افغان فالورز",
      hook: { ask: "کاملاً رایگان: ویدیوی سینمایی بردار، بدون دوربین", l1: "ویدیوی باکیفیت", l2: "رایگان و بدون کپی‌رایت" },
      payoff: "ویدیوی حرفه‌ای می‌گیری بدون دوربین و بدون هزینه.",
      steps: [
        { brand: {"name":"Pexels","url":"pexels.com/videos","color":"#05A081","tagline":"Free stock video"}, path: "pexels.com/videos", icon: "globe", text: "سایت پکسلز را باز کن", ui: { screen: "tool", url: "pexels.com/videos", cta: "جستجو" } },
        { path: "Search bar", icon: "target", text: "موضوع دلخواهت را جستجو کن", ui: { screen: "tool", url: "pexels.com/videos", cta: "جستجو" } },
        { path: "Filters > Vertical", icon: "phone", text: "فیلتر عمودی را بزن تا برای ریلز جور شود", ui: { screen: "tool", url: "pexels.com/videos", cta: "عمودی" } },
        { path: "Free Download", icon: "play", text: "دانلود کن و در تدوین استفاده کن", ui: { screen: "tool", url: "pexels.com/videos", cta: "دانلود" } },
      ],
      tgTitle: "🎥 ویدیوی حرفه‌ای و رایگان برای پس‌زمینهٔ ریلز\n\n#freeapp #editing #افغان_فالورز #viral",
    },
    {
      id: "ai-hook-writer",
      benefit: { key: "viral", fa: "قلاب ضعیف تا ۱۷ برابر بازدید می‌بلعد؛ ده گزینه بساز" },
      name: "AI Hooks",
      title: "ده قلاب در یک دقیقه — افغان فالورز",
      hook: { ask: "رایگان است — ده هوک قوی بساز تا اسکرول متوقف شود", l1: "برای هر ویدیو", l2: "ده شروع متفاوت بساز" },
      payoff: "شروع ویدیو مهم‌ترین سه ثانیه است؛ حالا ده گزینه داری.",
      steps: [
        { path: "claude.ai", icon: "globe", text: "یک دستیار هوش مصنوعی را باز کن", ui: { screen: "tool", url: "claude.ai", cta: "شروع گفتگو" } },
        { path: "New chat", icon: "pen", text: "موضوع ویدیو را بنویس", ui: { screen: "tool", url: "claude.ai", cta: "نوشتن موضوع" } },
        { path: "Ask for 10 hooks", icon: "bulb", text: "بخواه ده جملهٔ شروع کوتاه بسازد", ui: { screen: "tool", url: "claude.ai", cta: "ساخت ایده" } },
        { path: "Copy the best", icon: "magnet", text: "بهترین را بردار و همان را اول ویدیو بگو", ui: { screen: "tool", url: "claude.ai", cta: "انتخاب" } },
      ],
      tgTitle: "🪝 ده شروع متفاوت برای ویدیویت، در یک دقیقه\n\n#ai #contentcreator #افغان_فالورز #viral",
    },
  ],
};
